n = input('\033[1:35m''Digite algo ')
print(f'{'\033[1:36m'}Seu tipo é: {type(n)}')
print(f'É um número? {n.isnumeric()}')
print(f'É alfabético? {n.isalpha()}')
print(f'É um alfanumérico? {n.isalnum()}')
print(f'É um digito? {n.isdigit()}')
print(f'É uma letra maiúscula? {n.isupper()}')
print(f'É uma letra minúscula? {n.islower()}')
print(f'Está capitalizada? {n.istitle()}')
print(f'É uma tecla padrão? {n.isascii()}')
print(f'É um decimal? {n.isdecimal()}')
print(f'É apenas espaço? {n.isspace()}')
print(f'É visível na tela? {n.isprintable()}')
print(f'Pode ser nome de variável? {n.isidentifier()}')
